/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS `questions`;
CREATE DATABASE IF NOT EXISTS `questions` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `questions`;

CREATE TABLE IF NOT EXISTS `question` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `question` varchar(1024) DEFAULT NULL,
  `votes` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `uuid_votes` (
  `question_id` int(10) unsigned NOT NULL,
  `uuid` varchar(255) NOT NULL,
    PRIMARY KEY (`question_id`, `uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `uuid_rating` (
  `uuid` varchar(255) NOT NULL,
  `overall_rating` int(10) unsigned NOT NULL,
  `relevance_rating` int(10) unsigned NOT NULL,
  `entertaining_rating` int(10) unsigned NOT NULL,
    PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE USER 'questions'@'%' IDENTIFIED BY 'x2YfU8vHqAATS7Sh';
GRANT ALL PRIVILEGES ON questions.* TO 'questions'@'%';

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
